# Generated by Django 4.2.7 on 2024-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.AddField(
            model_name='amount',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
