# Generated by Django 4.2.7 on 2024-01-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_amount_name_amount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='currency',
            new_name='main_amount',
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='amount',
            new_name='user_amount',
        ),
    ]
