# Generated by Django 4.2.7 on 2024-01-27 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='main_amount',
        ),
        migrations.AlterField(
            model_name='amount',
            name='user_amount',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
