# Generated by Django 4.2.7 on 2024-01-27 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_remove_amount_main_amount_alter_amount_user_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='main_amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
