# Generated by Django 4.2.7 on 2024-01-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_amount_main_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='date_created',
        ),
    ]
