# Generated by Django 5.1.3 on 2026-04-05 18:34

import bank_app.models
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("USDT", "Tether (ERC20)"),
                            ("USDC", "USD Coin"),
                            ("BNB", "Binance Coin"),
                            ("SOL", "Solana"),
                            ("XRP", "Ripple"),
                            ("DOGE", "Dogecoin"),
                            ("TRX", "Tron"),
                            ("MATIC", "Polygon"),
                            ("LTC", "Litecoin"),
                            ("ADA", "Cardano"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("icon", models.CharField(default="fab fa-bitcoin", max_length=50)),
                (
                    "min_deposit",
                    models.DecimalField(decimal_places=8, default=0.001, max_digits=20),
                ),
                ("confirmations_required", models.IntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Cryptocurrencies",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic Plan"),
                            ("STANDARD", "Standard Plan"),
                            ("PREMIUM", "Premium Plan"),
                            ("VIP", "VIP Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=15),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=15
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("duration_days", models.IntegerField()),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemCryptoSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_approve_deposits", models.BooleanField(default=False)),
                (
                    "deposit_fee_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "min_deposit_amount",
                    models.DecimalField(decimal_places=8, default=10, max_digits=20),
                ),
                (
                    "max_deposit_amount",
                    models.DecimalField(
                        decimal_places=8, default=100000, max_digits=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "verbose_name": "System Crypto Setting",
                "verbose_name_plural": "System Crypto Settings",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_invested",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "expected_return",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bank_app.investmentplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INVESTMENT", "Investment"),
                            ("RETURN", "Return"),
                            ("BONUS", "Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bank_app.userinvestment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "refund_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "four_digit_auth_key",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("management", "Management"),
                            ("business_finance", "Business and Financial Operations"),
                            ("computer_math", "Computer and Mathematical"),
                            (
                                "architecture_engineering",
                                "Architecture and Engineering",
                            ),
                            ("life_sciences", "Life, Physical, and Social Sciences"),
                            ("community_social", "Community and Social Service"),
                            ("legal", "Legal"),
                            ("education", "Education, Training, and Library"),
                            (
                                "arts_design",
                                "Arts, Design, Entertainment, Sports, and Media",
                            ),
                            ("healthcare", "Healthcare Practitioners and Technical"),
                        ],
                        default="select your occupation",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("next_of_kin", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, max_length=255, null=True)),
                ("zip_code", models.IntegerField(blank=True, null=True)),
                (
                    "two_factor_auth",
                    models.CharField(
                        blank=True,
                        choices=[("enable", "Enable"), ("disable", "Disable")],
                        default="Enable",
                        max_length=10,
                    ),
                ),
                (
                    "card_application_fee_code",
                    models.CharField(
                        default=bank_app.models.generate_card_application_code,
                        max_length=16,
                    ),
                ),
                (
                    "cardholder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "card_number",
                    models.CharField(
                        default=bank_app.models.generate_card_number, max_length=16
                    ),
                ),
                (
                    "cvv",
                    models.CharField(
                        default=bank_app.models.generate_cvv, max_length=3
                    ),
                ),
                (
                    "expiry_date",
                    models.CharField(
                        default=bank_app.models.generate_expiry_date, max_length=7
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("United States", "United States"),
                            ("United Kingdom", "United Kingdom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "USD"),
                            ("€", "EUR"),
                            ("£", "GBP"),
                            ("₦", "NGN"),
                        ],
                        max_length=4,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Employed", "Employed"),
                            ("Unemployed", "Unemployed"),
                            ("Retired", "Retired"),
                            ("Student", "Student"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=50,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Online Account", "Online Account"),
                            ("Checking Account", "Checking Account"),
                            ("Current Account", "Current Account"),
                            ("Corporate Account", "Corporate Account"),
                            ("Offshore Account", "Offshore Account"),
                            ("Joint Account", "Joint Account"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "profile_pic",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="profile_pic",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        default=bank_app.models.generate_account_number, max_length=11
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "linking_code",
                    models.CharField(
                        default=bank_app.models.generate_code, max_length=11
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        default=bank_app.models.generate_otp, max_length=11
                    ),
                ),
                (
                    "imf_code",
                    models.CharField(
                        default=bank_app.models.generate_imf, max_length=11
                    ),
                ),
                (
                    "bic_code",
                    models.CharField(
                        default=bank_app.models.generate_aml, max_length=11
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_linked", models.BooleanField(default=False)),
                ("is_upgraded", models.BooleanField(default=False)),
                ("frozenState", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptoWalletAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=500, verbose_name="Wallet Address"),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ERC20", "Ethereum (ERC20)"),
                            ("TRC20", "Tron (TRC20)"),
                            ("BEP20", "Binance (BEP20)"),
                            ("SOL", "Solana"),
                            ("BTC", "Bitcoin"),
                            ("LTC", "Litecoin"),
                            ("XRP", "Ripple"),
                            ("DOGE", "Dogecoin"),
                            ("ADA", "Cardano"),
                            ("MATIC", "Polygon"),
                            ("AVAX", "Avalanche C-Chain"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_addresses",
                        to="bank_app.cryptocurrency",
                    ),
                ),
            ],
            options={
                "ordering": ["crypto__name", "-is_primary", "-created_at"],
                "unique_together": {("crypto", "address")},
            },
        ),
    ]
