# Generated by Django 5.1.3 on 2026-04-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="code",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("USDT", "Tether (ERC20)"),
                    ("USDC", "USD Coin"),
                    ("BSC", "BNB Binance Smart Chain (BEP20)"),
                    ("SOL", "Solana"),
                    ("XRP", "Ripple"),
                    ("DOGE", "Dogecoin"),
                    ("TRX", "Tron"),
                    ("MATIC", "Polygon"),
                    ("LTC", "Litecoin"),
                    ("ADA", "Cardano"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
