# Generated by Django 5.1.3 on 2026-04-05 22:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0003_alter_userprofile_country_alter_userprofile_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="refund_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10, null=True
            ),
        ),
    ]
